### ISSUE TITLE
兄弟，很及时啊hhh, 快点实现，我本来也想写个vscode版，太懒了, 帮你点star了

### ISSUE THREAD

**Issue by zhang-wangz** [ccagml/vscode-leetcode-problem-rating#1]
兄弟，你这创意抄的很及时啊hhh，快点实现，我本来也想写个vscode版，太懒了
我是那个浏览器插件作者，https://github.com/zhang-wangz/LeetCodeRating

**Comment by ccagml** [comment]
哈哈
