### ISSUE TITLE
can't log in leetcode.cn in m1 mac

### ISSUE THREAD

**Issue by yhsmer** [ccagml/vscode-leetcode-problem-rating#135]
## 🐛 Bug Report(错误报告)

can't log in leetcode.cn in m1 mac.
I can log in leetcode.cn with official leetcode extension, but can't log in using this extension.

## Extension Output(扩展输出)

Guidance: Press `Ctrl+Shift+U`, and toggle the channel to `LeetCode`.(按`Ctrl+Shift+U`，将频道切换到`LeetCode`。)
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/43242838/211179467-d8be075a-0f70-4751-94b5-9733313948f2.png">

## Your Environment

os: Darwin arm64 21.5.0
extension settings:
nodejs version: Node.js v18.8.0
vscode version: 1.74.2
extension version: v2.11.7

**Comment by ccagml** [comment]
This seems to be because the plug-in cannot obtain your username from https://leetcode.cn/list/api/questions, is it useless to log in again?
In addition, extension version: v0.18.1 I can't see which version of the plug-in is, is it the latest?
need more information.
thanks!

**Comment by yhsmer** [comment]
> In addition, extension version: v0.18.1 I can't see which version of the plug-in is, is it the latest? need more information. thanks!

Oh sorry, the version number is wrong, the version number I use is v2.11.7.

> This seems to be because the plug-in cannot obtain your username from https://leetcode.cn/list/api/questions, is it useless to log in again? 

I tried many times but couldn't log in, using cookies etc.


I can log in using the official plug-in(https://github.com/LeetCode-OpenSource/vscode-leetcode), indicating that there is no problem with my local network.

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/43242838/211811956-5d1071b4-906f-4767-afa1-9d03f9b5cf61.png">

**Comment by ccagml** [comment]
Hello yhsmer
I don't know why your account doesn't have favorites data
I updated 2.11.8, please try to see if it works
thanks!

**Comment by yhsmer** [comment]
<img width="982" alt="image" src="https://user-images.githubusercontent.com/43242838/211997662-21c8aa53-42c7-47b4-b174-3c8682e101c5.png">
Http error occurs when logging in with 2.11.8 (꒪⌓꒪) ,  but there are no proxy settings inside my vscode. 
It still doesn't work after I close my clash.

**Comment by ccagml** [comment]
(꒪⌓꒪) 2.11.9

**Comment by yhsmer** [comment]
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/43242838/212223185-4e7581fb-8248-44b6-b1b6-d719851972x25.png">

2.11.9还是无法工作，登录不上，且没给出具体提示。
和最开始的bug应该是一致的，“ [warn] favorite not found? ” 只是一个警告，应该不是导致登录不上的原因，我使用官方的插件也出现了这个warn，但是不影响使用。

**Comment by evankwolf** [comment]
可以看一下这里面的讨论有没有帮助
https://github.com/LeetCode-OpenSource/vscode-leetcode/issues/220

**Comment by ccagml** [comment]
@evankwolf 跟那个应该没关系,他之前的提示是因为获取不到标注的喜爱列表的内容数据,,我试了几个账号,都没有那种情况,他的账号不清楚是什么状况
我也没有m1 mac 所以不清楚跟m1 mac有没有关系

**Comment by ccagml** [comment]
@yhsmer 可以的话,可以看看你的根目录 ~/.lcpr/leetcode/user.json 的内容,是不是没有name的内容

**Comment by yhsmer** [comment]
> @yhsmer 可以的话,可以看看你的根目录 ~/.lcpr/leetcode/user.json 的内容,是不是没有name的内容

有内容，我的用户名就是yhsm，没有什么特殊的字符。
<img width="810" alt="image" src="https://user-images.githubusercontent.com/43242838/212301745-e3fbbe8d-2f59-40b8-a516-e612644bc5e9.png">

我之前一直使用的是这个插件https://marketplace.visualstudio.com/items?itemName=LeetCode.vscode-leetcode ，会不会是哪里出现了冲突。

**Comment by yhsmer** [comment]
并且，使用同样的用户名，我能登录leetcode.com账户（和.cn不是同一个账户），只是获取题目数据时会出bug
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/43242838/212306861-4b907715-56a7-410f-940f-5d10b5330b74.png">
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/43242838/212307161-531a83fd-7dd4-4088-a553-8c90410fc763.png">

**Comment by ccagml** [comment]
@yhsmer 你的user.json中login的内容是yhsm? 国服不是邮箱登录吗?

**Comment by yhsmer** [comment]
国服用户名登录和邮箱登录都登不上，.lcpr删了同样登不上，报错提示和前面一样😂

**Comment by ccagml** [comment]
Hello,麻烦再试试看2.11.10,我这边没有这种情况的账号,测不了😂

**Comment by yhsmer** [comment]
@ccagml 解决了！能登录了！
