### ISSUE TITLE
获取题目列表时，异常弹出语言选择框

### ISSUE THREAD

**Issue by Cinea4678** [ccagml/vscode-leetcode-problem-rating#136]
## 🐛 Bug Report(错误报告)

当插件启动时，或者手动刷新题目列表时，异常弹出语言选择框及错误信息

![语言选择框示意](https://blogsources-1305284863.file.myqcloud.com/images/%E6%88%AA%E5%B1%8F2023-01-08%2021.18.53.png)
语言选择框示意

![错误信息示意](https://blogsources-1305284863.file.myqcloud.com/images/%E6%88%AA%E5%B1%8F2023-01-08%2021.19.15.png)
错误信息示意

若选择默认语言，则不弹出语言选择框，但会收到以下提示信息：

![提示信息](https://blogsources-1305284863.file.myqcloud.com/images/%E6%88%AA%E5%B1%8F2023-01-08%2021.21.41.png)

## To Reproduce(重现)

手动刷新题目列表

## Extension Output(扩展输出)

扩展无异常输出。

## Your Environment

- *os(操作系统)*: macOS 13.1
- *extension settings(扩展设置)*: 无特殊设置
- *nodejs version(nodejs版本)*: v18.12.1
- *vscode version(vscode版本)*: 1.74.2 (Universal)
- *extension version(扩展版本)*: v2.11.5

**Comment by ccagml** [comment]
我更新了一下文件顺序 2.11.6
如果还有 Unexpected end of JSON input
需要你检查检查, 你的工作目录下的.lcpr_data目录下的bricks.json和group.json文件的内容是否是json格式
工作目录就是打开题目,题目文件存放的那个目录,vscode配置settings.json中leetcode-problem-rating.workspaceFolder的值
感谢
