### ISSUE TITLE
Plugin not found

### ISSUE THREAD

**Issue by juanyongjun** [ccagml/vscode-leetcode-problem-rating#16]
## 🐛 Bug Report(错误报告)

Extension not available, display Plugin not found

## To Reproduce(重现)

Click on Use extension

## Expected behavior(预期行为)
Extension not available

## Extension Output(扩展输出)

[ERROR] Plugin not found!
- Downloading https://raw.githubusercontent.com/leetcode-tools/leetcode-cli/master/lib/plugins/solution.discuss.js
[ERROR] Error: getaddrinfo ENOENT raw.githubusercontent.com

## Your Environment

- *os(操作系统)*:
- *extension settings(扩展设置)*:ubuntu20.04
- *nodejs version(nodejs版本)*:16
- *vscode version(vscode版本)*:1.67
- *extension version(扩展版本)*:1.0.13

**Comment by ccagml** [comment]
fix,thanks
