### ISSUE TITLE
测试用例不能是字符串

### ISSUE THREAD

**Issue by taotinggan** [ccagml/vscode-leetcode-problem-rating#18]
## 🐛 Bug Report(错误报告)

A clear and concise description of what the bug is.(清晰简洁地描述错误是什么。)
测试用例不能是字符串，会报错

## To Reproduce(重现)

Steps to reproduce the behavior.(重现的步骤。)
a
测试 输入"123"
## Expected behavior(预期行为)

A clear and concise description of what you expected to happen.(对您期望发生的事情进行清晰简洁的描述。)
正确执行

## Extension Output(扩展输出)

Paste here the LeetCode extension log from output channel.(将输出通道中的 LeetCode 扩展日志粘贴到此处。)

Guidance: Press `Ctrl+Shift+U`, and toggle the channel to `LeetCode`.(按`Ctrl+Shift+U`，将频道切换到`LeetCode`。)
123 is not a valid value of type string

## Your Environment

- *os(操作系统)*:window10
- *extension settings(扩展设置)*:
- *nodejs version(nodejs版本)*:16
- *vscode version(vscode版本)*:
- *extension version(扩展版本)*:1.0.15

**Comment by ccagml** [comment]
1.0.16修复了
