### ISSUE TITLE
题目元数据显示出错

### ISSUE THREAD

**Issue by Cinea4678** [ccagml/vscode-leetcode-problem-rating#43]
## 🐛 Bug Report(错误报告)

![Sample Image](https://blogsources-1305284863.file.myqcloud.com/MainPage/20221022233017.png)
Bug样图

在显示题目元数据时，会出现如图所示错误。

## To Reproduce(重现)

正常打开一道题目即会出现

## Extension Output(扩展输出)

```
[%s] %s %s 1751 最多可以参加的会议数目 II icon.empty

https://leetcode.cn/problems/maximum-number-of-events-that-can-be-attended-ii/description/

Tags:   algorithms 

Langs:  c   cpp   csharp   dart   elixir   erlang   golang   java   javascript   kotlin   php   python   python3   racket   ruby   rust   scala   swift   typescript 

* %s algorithms
* %s (%s%%) Hard 52.49
* Likes:    %s 63
* Dislikes: -
* Total Accepted:    %s 5.2K
* Total Submissions: %s 9.9K
* Testcase Example:  %s '[[1,2,4],[3,4,3],[2,3,1]]\n2'

（省略其他无关的输出）
```

## Your Environment

- *os(操作系统)*: Windows 11 22H2
- *extension settings(扩展设置)*:  默认设置
- *nodejs version(nodejs版本)*:  v16.13.0
- *vscode version(vscode版本)*:  1.17.2
- *extension version(扩展版本)*:  v1.1.4

**Comment by ccagml** [comment]
修复了,1.1.5 谢谢
