### ISSUE TITLE
手动输入测试用例时处理异常

### ISSUE THREAD

**Issue by Cinea4678** [ccagml/vscode-leetcode-problem-rating#46]
## 🐛 Bug Report(错误报告)

手动输入测试用例时，输入内容被错误地作为一个完整的字符串传递。

![异常表现](https://blogsources-1305284863.file.myqcloud.com/MainPage/GIF2022-11-210-42-58.gif)
异常表现

![对照-官方版本插件](https://blogsources-1305284863.file.myqcloud.com/MainPage/GIF2022-11-210-47-51.gif)
对照-官方版本插件

## To Reproduce(重现)

使用“手动输入测试用例”即可触发异常

## Extension Output(扩展输出)

```
{"messages":["Runtime Error"],"system_message":{"fid":"198","id":198,"qid":198,"sub_type":"test","accepted":false},"Error":["\"[1,2,2,1]\" is not a valid value of type integer[]","\"[1,2,2,1]\" is not a valid value of type integer[]"],"Your Input":["\"[1,2,2,1]\""],"Stdout":[""]}
```

## Your Environment

- *os(操作系统)*: Windows 11
- *nodejs version(nodejs版本)*: v16.13.0
- *vscode version(vscode版本)*: 1.72.2
- *extension version(扩展版本)*:  v1.1.6

**Comment by ccagml** [comment]
修复了,1.1.7 谢谢
