### ISSUE TITLE
题目更新慢，不实时同步最新题目？

### ISSUE THREAD

**Issue by JiaoZiLang** [ccagml/vscode-leetcode-problem-rating#49]

**Comment by JiaoZiLang** [comment]
![image](https://user-images.githubusercontent.com/9896920/199691710-34872c35-d095-493a-b1b0-5a4521def9b9.png)
![image](https://user-images.githubusercontent.com/9896920/199691799-a617b203-a1fa-420e-88d9-76775bd4bd69.png)

**Comment by ccagml** [comment]
这个是原本插件就有的问题,因为题目数据很大,不好每次打开插件就请求所有题目的数据
重新登录账号就会有新的题目了

**Comment by JiaoZiLang** [comment]
并不是这样哦。依据：
1. 从日志看题目已经拉下来了
![image](https://user-images.githubusercontent.com/9896920/199872953-3778c73e-f7b5-49fa-81b0-aa5f3f978f7b.png)
2.最新题目ID
![image](https://user-images.githubusercontent.com/9896920/199873054-bd31a605-91eb-448d-96b8-21381be51b6d.png)

判断结论：
插件没展示最新的题目

**Comment by ccagml** [comment]
不好意思，关掉issues会收不到你的消息
看你的显示，你是勾选了配置中只显示有分数的题目吗？
那几题的分数我提交了
感谢
