### ISSUE TITLE
vsode

### ISSUE THREAD

**Issue by yuanzhimengbian** [ccagml/vscode-leetcode-problem-rating#83]
## 🐛 Bug Report(错误报告)

A clear and concise description of what the bug is.(清晰简洁地描述错误是什么。)

## To Reproduce(重现)

Steps to reproduce the behavior.(重现的步骤。)
a
## Expected behavior(预期行为)

A clear and concise description of what you expected to happen.(对您期望发生的事情进行清晰简洁的描述。)

## Extension Output(扩展输出)

Paste here the LeetCode extension log from output channel.(将输出通道中的 LeetCode 扩展日志粘贴到此处。)

Guidance: Press `Ctrl+Shift+U`, and toggle the channel to `LeetCode`.(按`Ctrl+Shift+U`，将频道切换到`LeetCode`。)

## Your Environment

- *os(操作系统)*:
- *extension settings(扩展设置)*:
- *nodejs version(nodejs版本)*:
- *vscode version(vscode版本)*:
- *extension version(扩展版本)*:

**Comment by ccagml** [comment]
看了一下，网站还在的，应该是被墙了

**Comment by yuanzhimengbian** [comment]
科学上网就能访问到了吗

**Comment by ccagml** [comment]
应该是的

**Comment by yuanzhimengbian** [comment]
但是挂上代理也不行

**Comment by ccagml** [comment]
我改了一下,如果获取超过2秒就不获取了,避免一直卡着等那个数据
